---
driver:
    name: vagrant

provisioner:
#  ansible_platform: ubuntu
  name: ansible_playbook
#  roles_path:
  hosts: test-kitchen
  require_ansible_repo: true
  ansible_version: latest

  ansible_verbose: true
  ansible_verbosity: 4
  sudo: true
  extra_vars:
    a: b

platforms:
  #- name: ubuntu-10.04 # lucid # Tested but bento box disappeared
  ## omnibus-ansible and other install methods
  ## no longer work due to pip package dep issue.
  ## Tracked in neillturner/omnibus-ansible#9
  - name: ubuntu-12.04 # precise # Tested, but new ansible package cannot install
    provisioner:
      require_ansible_omnibus: false
      require_ansible_repo: false
      require_pip: true
      custom_pre_install_command: 'sudo -E apt-get -y install python-setuptools && sudo -E  easy_install -i https://pypi.python.org/simple pip'
  #- name: ubuntu-13.10 # saucy # Tested but bento box disappeared
  - name: ubuntu-14.04 # trusty
  - name: ubuntu-16.04 # xenial
  # - name: centos-5.10 # TODO: NOT TESTED YET... unsure if kitchen-ansible works yet...
  - name: centos-6.4
  - name: centos-6.5
  - name: centos-7.1
  # - name: nocm_centos-6.5
  #   driver_plugin: vagrant
  #   driver_config:
  #     box: nocm_centos-6.5
  #     box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
      # network:
      #  - ['forwarded_port', {guest: 8080, host: 8080}]
      #  - [ 'private_network', { ip: '192.168.33.11' } ]

suites:
 - name: default
