---
driver:
  name: docker
## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-16.04
#    driver_config: &UBUNTU_PROVISION
#      provision_command:
#      - apt-get -y install apt-utils
#      - apt-get -y install software-properties-common python-software-properties
#      - add-apt-repository ppa:rquillo/ansible
#      - curl -L https://www.opscode.com/chef/install.sh | bash
#      - apt-get update
#      - apt-get -y install python-selinux
#      - curl -L https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh | bash
#      - apt-get install -y build-essential bash debianutils dnsutils net-tools telnet tar cron
#  - name: ubuntu-14.04  # omnibus-ansible fails to install
#    driver_config: *UBUNTU_PROVISION
#  - name: ubuntu-12.04  # omnibus-ansible fails to install
#    driver_config: *UBUNTU_PROVISION
  - name: centos-7
    driver_config: &SYSTEMD_INIT
      run_command: /usr/sbin/init
      run_options:
        - volume: "/sys/fs/cgroup:/sys/fs/cgroup"
        - "--privileged"
### epel mirror issue. see readme
#  - name: centos-6
### Ansible 2.2+/cryptography: https://github.com/ansible/ansible/issues/276
#    provisioner:
#      ansible_version: 2.1.2.0
## tool chain kitchen and image need customization... nok currently
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:

